name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Determine tag based on branch
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch


    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/falkor:${{ steps.extract_branch.outputs.branch }}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/falkor:${{ steps.extract_branch.outputs.branch }} ${{ secrets.DOCKERHUB_USERNAME }}/falkor:latest

    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push both tags of the image to DockerHub
    - name: Push the images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/falkor:${{ steps.extract_branch.outputs.branch }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/falkor:latest
