name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Determine tag based on branch
    - name: Set Docker Image Tag
      id: set_tag
      run: |
        if [[ $GITHUB_REF == refs/heads/dev ]]; then
          echo "tag=dev" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.run_number }}" >> $GITHUB_OUTPUT

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/falkor:${{ env.tag }}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/falkor:${{ env.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/falkor:latest

    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push both tags of the image to DockerHub
    - name: Push the images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/falkor:${{ env.tag }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/falkor:latest
